config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show]
  get 'react', to: 'portfolios#react'
  get 'ruby_on_rails', to: 'portfolios#ruby_on_rails'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  root 'pages#home'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get 'toggle_status'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies, dependent: :destroy
  accepts_nested_attributes_for :technologies, reject_if: lambda { |attrs|
    attrs['name'].blank?
  }
  include Placeholder

  validates :title, :body, :main_image, :thumb_image, presence: true
  def self.react
    where(subtitle: 'React')
  end

  def self.by_position
    order('position ASC')
  end
  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby on Rails') }

  after_initialize :set_defaults
  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: %i[show edit update destroy]
  access all: %i[show index react ruby_on_rails], user: { except: %i[destroy new create update edit] }, site_admin: :all

  layout 'portfolio'
  def index
    @portfolio_items = Portfolio.by_position
    @page_title = 'My Portfolio'
  end

  def react
    @react_portfolio_items = Portfolio.react
  end

  def ruby_on_rails
    @ruby_on_rails_portfolio_items = Portfolio.ruby_on_rails_portfolio_items
  end

  def show
    @page_title = @portfolio_item.title
  end

  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  def edit
    3.times { @portfolio_item.technologies.build }
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio item was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)
    respond_to do |format|
      if @portfolio_item.save

        format.html { redirect_to portfolios_path, notice: 'Portfolio item was successfully created.' }

        format.json { render :show, status: :created, location: @portfolio_item }
      else
        format.html { render :new }
        format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio item was removed.' }
    end
  end

  private

  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end

  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      :main_image,
                                      :thumb_image,
                                      technologies_attributes: [:name])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
<div class="field">
    <%= f.text_field :title, placeholder: "Title" %>
</div>
<div class="field">
    <%= f.text_field :subtitle, placeholder: "Subtitle"  %>
</div>
<div class="field">
    <%=  f.text_area :body, placeholder: "Body"  %>
</div>
<div class="field">
    <%= f.text_field :thumb_image, placeholder: "Thumb Image"  %>
</div>
<div class="field">
    <%= f.text_field :main_image, placeholder: "Main Image"  %>
</div>
<ul>
    <%= f.fields_for :technologies do |technology_form| %>
    <li><%= technology_form.text_field :name, placecholder: "Technology" %></li>
    <% end %>
</ul>
<div class="action">
    <%= f.submit %>
</div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col sortable" data-id="<%= portfolio_item.id %>">
    <h2><%=link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></h2>
    <h4><%= portfolio_item.subtitle %></h4>
    <div class="card shadow-sm">
        <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil?%>
        <div class="card-body">
            <p class="card-text"><%= portfolio_item.body %></p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <%= link_to 'edit',  edit_portfolio_path(portfolio_item), class:"btn btn-sm btn-outline-secondary"  if logged_in?(:site_admin)%>
                    <%= link_to 'remove',  portfolios_path(portfolio_item), data: { 
                                                                            turbo_method: :delete,confirm: 'Are you sure?' } , class:"btn btn-sm btn-outline-secondary"if logged_in?(:site_admin)%>
                </div>
                <small class="text-muted">9 mins</small>
            </div>
        </div>
    </div>
</div>

app/views/portfolios/edit.html.erb
<h1>Update Portfolio item</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/index.html.erb
<%= link_to 'new',  new_portfolio_path  if logged_in?(:site_admin)%>

<%= render partial: 'portfolio_item', collection: @portfolio_items %>

app/views/portfolios/new.html.erb
<h1>Create new Portfolio item</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/react.html.erb
<h2>React </h2>
<% @react_portfolio_items.each do |item| %>
<h2><%=link_to item.title, portfolio_show_path(item) %></h2>
<h4><%= item.subtitle %></h4>
<p><%= item.body %></p>
<%= image_tag item.thumb_image unless item.thumb_image.nil?%>
<%= link_to 'edit',  edit_portfolio_path(item) %>
<%= link_to 'remove',  portfolio_path(item), method: :delete , data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) if logged_in?(:site_admin)%>
<% end %>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio_item.main_image unless @portfolio_item.main_image.nil? %>
<h1><%= @portfolio_item.title %></h1>
<h3><%= @portfolio_item.subtitle %></h3>
<p><%= @portfolio_item.body %></p>
<hr>
<h2>Technologies used</h2>
<% @portfolio_item.technologies.each do |technology_item| %>
<h5><%= technology_item.name %></h5>
<% end %>
<%= render 'shared/links' %>