config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show]
  get 'react', to: 'portfolios#react'
  get 'ruby_on_rails', to: 'portfolios#ruby_on_rails'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  root 'pages#home'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get 'toggle_status'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_application_footer.html.erb
<footer class="mt-auto text-white-50 footer-possitioning">
    <%= @copyright %>
</footer>

app/views/shared/_application_nav.html.erb
<header class="mb-auto">
    <div>
        <h3 class="float-md-start mb-0 margin-header">Pawel Maryon</h3>

        <nav class="nav nav-masthead justify-content-center float-md-end">
            <%= link_to 'home' , root_path, class: "nav-link active" %>
            <%= link_to 'about-me',  about_me_path, class:"nav-link" %>
            <%= link_to 'contact',  contact_path, class:"nav-link" %>
            <%= link_to 'blogs',  blogs_path, class:"nav-link" %>
            <%= link_to 'portfolio',  portfolios_path, class:"nav-link" %>
            <%= login_helper("nav-link" ) %>
        </nav>
    </div>
</header>

app/views/shared/_blog_nav.html.erb
<div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
        <%= link_to 'home',  root_path, class: "p-2 link-secondary" %>
        <%= link_to 'about-me',  about_me_path, class:"p-2 link-secondary" %>
        <%= link_to 'contact',  contact_path, class:"p-2 link-secondary" %>
        <%= link_to 'blogs',  blogs_path, class:"p-2 link-secondary" %>
        <%= link_to 'portfolio',  portfolios_path, class:"p-2 link-secondary" %>   
    </nav>
</div>

app/views/shared/_links.html.erb
<%= link_to 'new',  new_portfolio_path if logged_in?(:site_admin) %>
<%= link_to 'edit',  edit_portfolio_path(@portfolio_item) if logged_in?(:site_admin) %>
<%= link_to 'home',  portfolios_path %>
<%= link_to 'remove',  portfolios_path if logged_in?(:site_admin) %>

app/views/shared/_navbar.html.erb
<div>
    <nav class="nav nav-masthead justify-content-center float-md-end">
        <%= link_to 'home',  root_path, class: "nav-link active" %>
        <%= link_to 'about-me',  about_me_path, class:"nav-link" %>
        <%= link_to 'contact',  contact_path, class:"nav-link" %>
        <%= link_to 'blogs',  blogs_path, class:"nav-link" %>
        <%= link_to 'portfolio',  portfolios_path, class:"nav-link" %>
        <%= login_helper("nav-link") %>
    
    </nav>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted py-5">
    <div class="container">
        <p class="mb-1"><%= @copyright %></p>
        <i class="fab fa-facebook-square"></i>
        
    </div>
</footer>

app/views/shared/_portfolio_nav.html.erb
<header>
        <div class="collapse bg-dark" id="navbarHeader">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 col-md-7 py-4">
                        
                        <h4 class="text-white">About</h4>
                        <p class="text-muted">I have placed all my work here. Clicking on projects will take you to specific GitHub repository or to proects website if deployed.</p>
                    </div>
                    <div class="col-sm-4 offset-md-1 py-4">
                        <h4 class="text-white">Contact</h4>
                        <ul class="list-unstyled">
                            <li><%= link_to 'home',  root_path, class: "text-white" %></li> 
                            <li><%= link_to 'about-me',  about_me_path, class: "text-white" %></li> 
                            <li><%= link_to 'contact',  contact_path, class: "text-white" %></li> 
                            <li><%= link_to 'blogs',  blogs_path, class: "text-white" %></li> 
                            <li><%= link_to 'portfolio',  portfolios_path, class: "text-white" %></li>   
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="navbar navbar-dark bg-dark shadow-sm">
            <div class="container">
                <a href="#" class="navbar-brand d-flex align-items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24">
                        <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z" />
                        <circle cx="12" cy="13" r="4" /></svg>
                    <strong>Portfolio</strong>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
            </div>
        </div>
    </header>

app/views/shared/_portfolio_navbar.html.erb
<header>
        <div class="collapse bg-dark" id="navbarHeader">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 col-md-7 py-4">
                        
                        <h4 class="text-white">About</h4>
                        <p class="text-muted">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Error molestiae hic reprehenderit, dolorem recusandae pariatur vero atque saepe ullam. Necessitatibus iste cupiditate labore impedit voluptatum aperiam quas molestias autem fuga et repellat assumenda, sed quam minus laborum laudantium dignissimos nesciunt architecto ex nisi! Saepe suscipit doloribus autem culpa, laboriosam quasi!</p>
                    </div>
                    <div class="col-sm-4 offset-md-1 py-4">
                        <h4 class="text-white">Contact</h4>
                        <ul class="list-unstyled">
                            <li><a href="#" class="text-white">Follow on Twitter</a></li>
                            <li><a href="#" class="text-white">Like on Facebook</a></li>
                            <li><a href="#" class="text-white">Email me</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="navbar navbar-dark bg-dark shadow-sm">
            <div class="container">
                <a href="#" class="navbar-brand d-flex align-items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24">
                        <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z" />
                        <circle cx="12" cy="13" r="4" /></svg>
                    <strong>Album</strong>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>
    </header>